### PR TITLE
[12.0] Add pre_commit hook

### PR DESCRIPTION
**Pull request by lmignon**
will be finalized once #47 is merged into 12.0
Blocked by:
* [x] #47

Includes:
* [x] #49

### CODE REVIEW

**Comment by simahawk** [comment]
:heart: then you'll have to push on OCA to adopt it :smile:

**Comment by lmignon** [comment]
@simahawk We plan to move this repo to OCA soon... 
We are working on elasticsearch and at the same time we are cleaning the repo to have the same code in 10 and 12

**Comment by simahawk** [comment]
@lmignon I see, but using black might be a barrier to move to OCA. Although is going to happen "in our playground" in a separated repo...

**Comment by lmignon** [comment]
@simahawk IMO if it's a barrier, we should move this repo to https://github.com/shopinvader

**Comment by simahawk** [comment]
> @simahawk IMO if it's a barrier, we should move this repo to https://github.com/shopinvader

what I'm saying is that we should probably open the discussion before (on MQT?) to see if we can keep it in an OCA repo.

**Comment by lmignon** [comment]
> what I'm saying is that we should probably open the discussion before (on MQT?) to see if we can keep it in an OCA repo.

For sure. We should also open the discussion on MQT itself and the way it's used into travis.. I've just discovered that the way pytlint-odoo is installed and/or launched  by MQT doesn't work if you have a '.isort.cfg' file at the root of the repository. But this kind of discussion seems almost impossible to me in the OCA

**Comment by lmignon** [comment]
@simahawk @sebastienbeau This one is ready for review. The most important part is https://github.com/akretion/connector-search-engine/pull/50/commits/89becd55fe814782afe80521ac9bc883a18b50b1

I've kept the same limit as into OCA for the max-line-length so we can continue to use MQT to check the code quality and ensure that we follow the same rules as into OCA

**Comment by sebastienbeau** [comment]
@simahawk as we use black but with the same max-line as OCA guide line, I do not think that this will be blocking in the OCA.

**Pull request merged**
