### PR TITLE
[FIX] connector_alogolia: Fix button into form view

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
this follows the change in d62fab544af188ec714bd56aeabdce45b61bc221
tested locally

**Comment by yvaucher** [comment]
This one can be cancelled if https://github.com/akretion/connector-search-engine/pull/35 is merged

**Review by yvaucher — CHANGES_REQUESTED** [review]
.

**Review by yvaucher — CHANGES_REQUESTED** [review]
I'll reject it in favor of https://github.com/akretion/connector-search-engine/pull/35

**Comment by yvaucher** [comment]
( ok not used to have my request changes as comment, consider my previous reviews as :stop_sign: )

**Comment by sebastienbeau** [comment]
close as #35 has been merged

**Pull request closed without merging**
